executable = condor_gof_test.sh
arguments = $(ProcId)
output                = gof_test.$(ClusterId).$(ProcId).out
error                 = gof_test.$(ClusterId).$(ProcId).err
log                   = gof_test.$(ClusterId).log

# Send the job to Held state on failure.
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)

# Periodically retry the jobs every 10 minutes, up to a maximum of 5 retries.
periodic_release =  (NumJobStarts < 3) && ((CurrentTime - EnteredCurrentStatus) > 600)


queue 1

